<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111827; }
        h1, h2, h3 { margin: 0; }
        h1 { font-size: 20px; }
        h2 { font-size: 14px; margin-top: 4px; color: #374151; }
        table { width: 100%; border-collapse: collapse; margin-top: 14px; }
        th, td { border: 1px solid #d1d5db; padding: 6px; vertical-align: top; }
        th { background: #f3f4f6; text-align: left; font-weight: bold; }
        .header { border-bottom: 2px solid #047857; padding-bottom: 10px; margin-bottom: 12px; }
        .brand-table { width: 100%; border-collapse: collapse; margin: 0; }
        .brand-table td { border: 0; padding: 0; vertical-align: middle; }
        .brand-logo { width: 52px; max-height: 52px; object-fit: contain; padding-right: 10px; }
        .muted { color: #6b7280; }
        .summary { display: table; width: 100%; margin-top: 12px; }
        .summary-card { display: table-cell; border: 1px solid #d1d5db; padding: 8px; width: 20%; }
        .summary-card strong { display: block; font-size: 14px; margin-top: 2px; }
        .right { text-align: right; }
        .center { text-align: center; }
        .footer { margin-top: 18px; font-size: 10px; color: #6b7280; }
    </style>
</head>
<body>
@php($company = $company ?? app(\App\Services\Company\CompanyInformationService::class)->reportHeader())
<div class="header">
    <table class="brand-table">
        <tr>
            @if($company['logo_data_uri'] ?? null)
                <td style="width: 62px;">
                    <img src="{{ $company['logo_data_uri'] }}" class="brand-logo" alt="">
                </td>
            @endif
            <td>
                <h1>{{ $company['name'] }}</h1>
                @if($company['address'] ?? null)
                    <div class="muted">{{ $company['address'] }}</div>
                @endif
                <h2>Fund Utilization Report (FUR)</h2>
                <div class="muted">
                    {{ $fund?->location ?? 'All Imprest Funds' }} | {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}
                </div>
                <div class="muted">
                    Generated by {{ $generatedBy?->name ?? 'System' }} on {{ $generatedAt->format('d M Y, h:i A') }}
                </div>
            </td>
        </tr>
    </table>
</div>

<table>
    <tr>
        <th>Fund</th>
        <td>{{ $fund?->location ?? 'All Funds' }}</td>
        <th>Zone</th>
        <td>{{ $fund?->zone?->name ?? 'N/A' }}</td>
        <th>Custodian</th>
        <td>{{ $fund?->custodian?->name ?? 'N/A' }}</td>
    </tr>
    <tr>
        <th>Bank</th>
        <td colspan="5">{{ $fund?->bankAccount?->account_name ?? 'N/A' }}</td>
    </tr>
</table>

<div class="summary">
    <div class="summary-card">
        <span class="muted">Authorized</span>
        <strong>NGN {{ number_format($summary['authorized_amount'], 2) }}</strong>
    </div>
    <div class="summary-card">
        <span class="muted">Current Balance</span>
        <strong>NGN {{ number_format($summary['current_balance'], 2) }}</strong>
    </div>
    <div class="summary-card">
        <span class="muted">Spent In Period</span>
        <strong>NGN {{ number_format($summary['total_spent'], 2) }}</strong>
    </div>
    <div class="summary-card">
        <span class="muted">Transactions</span>
        <strong>{{ number_format($summary['transaction_count']) }}</strong>
    </div>
    <div class="summary-card">
        <span class="muted">Missing Receipts</span>
        <strong>{{ number_format($summary['missing_receipts']) }}</strong>
    </div>
</div>

<table>
    <thead>
    <tr>
        <th>Date</th>
        <th>Voucher</th>
        <th>Deceased / Family</th>
        <th>Item / Service</th>
        <th>Category</th>
        <th class="right">Qty</th>
        <th class="right">Unit Price</th>
        <th class="right">Total</th>
        <th>Receipt</th>
        <th>Approved By</th>
    </tr>
    </thead>
    <tbody>
    @forelse($transactions as $transaction)
        <tr>
            <td>{{ $transaction->date?->format('d M Y') }}</td>
            <td>{{ $transaction->voucher_no }}</td>
            <td>{{ $transaction->beneficiary_name }}</td>
            <td>{{ $transaction->expense_description }}</td>
            <td>{{ ucfirst(str_replace('_', ' ', $transaction->category)) }}</td>
            <td class="right">{{ number_format((float) $transaction->quantity, 2) }}</td>
            <td class="right">{{ number_format((float) $transaction->unit_price, 2) }}</td>
            <td class="right">{{ number_format((float) $transaction->total_price, 2) }}</td>
            <td class="center">{{ $transaction->receipt_attached ? 'Yes' : 'No' }}</td>
            <td>{{ $transaction->approver?->name ?? 'N/A' }}</td>
        </tr>
    @empty
        <tr>
            <td colspan="10" class="center">No active imprest transactions found for this period.</td>
        </tr>
    @endforelse
    </tbody>
    <tfoot>
    <tr>
        <th colspan="7" class="right">Total</th>
        <th class="right">{{ number_format($summary['total_spent'], 2) }}</th>
        <th colspan="2"></th>
    </tr>
    </tfoot>
</table>

<div class="footer">
    This report is generated from approved imprest transactions only. Voided and pending transactions are excluded.
</div>
</body>
</html>
