<?php

namespace App\Filament\Resources\Deceased\RelationManagers;

use App\Models\Widow;
use App\Services\RegistrationNumberService;
use Filament\Actions\Action;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\CreateAction;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TagsInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Tables;
use Filament\Tables\Table;

class WidowsRelationManager extends RelationManager
{
    protected static string $relationship = 'widows';
    protected static ?string $recordTitleAttribute = 'full_name';
    protected static ?string $title = 'Widows';
    protected static string|null|\BackedEnum $icon = 'heroicon-o-heart';

    public function form(Schema $schema): Schema
    {
        return $schema
            ->schema([
                // Section: Personal Information - Full width to allow names to breathe
                Section::make('Personal Information')
                    ->description('Primary identification and registration details.')
                    ->icon('heroicon-m-user-circle')
                    ->schema([
                        Grid::make(3)
                            ->schema([
                                TextInput::make('first_name')
                                    ->required()
                                    ->maxLength(100),
                                TextInput::make('middle_name')
                                    ->maxLength(100),
                                TextInput::make('last_name')
                                    ->required()
                                    ->maxLength(100),
                            ]),

                        Grid::make(2)
                            ->schema([
                                TextInput::make('nin')
                                    ->label('NIN')
                                    ->required()
                                    ->unique(ignoreRecord: true)
                                    ->placeholder('Enter 11-digit NIN')
                                    ->maxLength(11),

                                TextInput::make('reg_no')
                                    ->label('Registration Number')
                                    ->placeholder('Auto-generated')
                                    ->disabled() // Generated by service
                                    ->dehydrated(false),
                            ]),
                    ]),

                // Section: Status & Skills - Side by side layout
                Section::make('Professional & Eligibility Status')
                    ->icon('heroicon-m-briefcase')
                    ->schema([
                        Grid::make(2)
                            ->schema([
                                TagsInput::make('skills')
                                    ->label('Skills / Profession')
                                    ->placeholder('Type and press enter (e.g. Tailoring, Nursing)')
                                    ->columnSpan(1),

                                FileUpload::make('picture_url')
                                    ->label('Profile Photo')
                                    ->image()
                                    ->disk('public')
                                    ->directory('widow-photos')
                                    ->visibility('public')
                                    ->nullable()
                                    ->storeFileNamesIn('picture_original_name') // optional but stabilizes state
                                    ->dehydrated(true)
                                    ->preserveFilenames()
                                    ->imageEditor()
                                    ->circleCropper(),
                            ]),

                        Grid::make(2)
                            ->schema([
                                Toggle::make('is_eligible')
                                    ->label('Eligible for Social Support')
                                    ->helperText('Verify if this widow meets standard criteria for intervention.')
                                    ->default(true),

                                Toggle::make('is_married')
                                    ->label('Remarried')
                                    ->helperText('Switch on if the widow has entered a new marriage.')
                                    ->default(false),
                            ]),
                    ]),

                // Section: Contact - Large textarea for long addresses
                Section::make('Residential Address')
                    ->icon('heroicon-m-home')
                    ->schema([
                        Textarea::make('address')
                            ->label('Physical Address')
                            ->placeholder('Street name, house number, and notable landmarks...')
                            ->rows(4)
                            ->required()
                            ->columnSpanFull(),
                    ]),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\ImageColumn::make('picture_url')
                    ->disk('public')
                    ->visibility('public')
                    ->circular()
                    ->imageSize(40),

                Tables\Columns\TextColumn::make('full_name')
                    ->label('Name')
                    ->searchable(['first_name', 'middle_name', 'last_name'])
                    ->sortable()
                    ->weight('bold'),

                Tables\Columns\TextColumn::make('nin')
                    ->label('NIN')
                    ->searchable()
                    ->copyable()
                    ->fontFamily('mono'),

                Tables\Columns\TextColumn::make('reg_no')
                    ->label('Reg No')
                    ->searchable()
                    ->badge(),

                Tables\Columns\IconColumn::make('is_eligible')
                    ->label('Eligible')
                    ->boolean()
                    ->alignCenter(),

                Tables\Columns\TextColumn::make('skills')
                    ->label('Skills')
                    ->badge()
                    ->separator(',')
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->headerActions([
                CreateAction::make()
                    ->label('Add Widow')
                    ->icon('heroicon-m-plus')
                    ->modalWidth('4xl') // Makes the creation modal wider for better layout
                    ->mutateDataUsing(function (array $data, RelationManager $livewire): array {

                        $deceased = $livewire->getOwnerRecord();

                        $generated = app(RegistrationNumberService::class)
                            ->generateWidowData($deceased);

                        return array_merge($data, $generated);
                    })
                    ->hidden(fn (RelationManager $livewire) => $livewire->getRelationship()->count() >= 4),
            ])
            ->recordActions([
                // NEW: MEDICAL RECORDS ACTION
                Action::make('manageMedical')
                    ->label('Medical Records')
                    ->icon('heroicon-m-beaker')
                    ->color('success')
                    ->modalHeading(fn (Widow $record) => "Prescriptions for {$record->full_name}")
                    ->modalWidth('5xl')
                    ->modalSubmitActionLabel('Save Records')
                    ->schema([
                        Repeater::make('prescriptions')
                            ->relationship('prescriptions')
                            ->schema([
                                Grid::make(3)->schema([
                                    TextInput::make('doctor_name')
                                        ->required(),
                                    TextInput::make('illness')
                                        ->label('Diagnosis')
                                        ->required(),
                                    DatePicker::make('prescription_date')
                                        ->default(now())
                                        ->required(),
                                ]),
                                Grid::make(2)->schema([
                                    TextInput::make('lab_test_cost')
                                        ->numeric()
                                        ->prefix('₦')
                                        ->default(0),
                                    TextInput::make('drug_cost')
                                        ->numeric()
                                        ->prefix('₦')
                                        ->default(0),
                                ]),
                                Select::make('medications')
                                    ->multiple()
                                    ->relationship('medications', 'name')
                                    ->preload()
                                    ->searchable()
                                    ->hint('Select prescribed drugs from pharmacy master list.'),
                                Textarea::make('note')
                                    ->rows(2)
                                    ->placeholder('Dosage instructions or clinical notes...')
                                    ->columnSpanFull(),

                                // Hidden field to track who is issuing
                                Hidden::make('user_id')
                                    ->default(auth()->id()),
                            ])
                            ->itemLabel(fn (array $state): ?string => $state['illness'] ?? null)
                            ->collapsible()
                            ->collapsed()
                            ->cloneable()
                            ->addActionLabel('New Prescription'),
                    ])
                    ->action(function (Widow $record): void {
                        $record->touch(); // Refreshes timestamps to trigger UI update
                    }),

                ViewAction::make(),
                EditAction::make()->modalWidth('4xl'),
                DeleteAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
