<?php

namespace App\Filament\Resources\Deceased\RelationManagers;

use App\Enums\IllnessCategory;
use App\Models\Illness;
use App\Models\Medication;
use App\Models\Prescription;
use App\Models\Widow;
use App\Services\RegistrationNumberService;
use Filament\Actions\Action;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\CreateAction;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TagsInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Notifications\Notification;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Support\Facades\Schema as DatabaseSchema;

class WidowsRelationManager extends RelationManager
{
    protected static string $relationship = 'widows';

    protected static ?string $recordTitleAttribute = 'full_name';

    protected static ?string $title = 'Widows';

    protected static ?string $relatedRecordTitleAttribute = 'full_name';

    protected static string|null|\BackedEnum $icon = 'heroicon-o-heart';

    public function form(Schema $schema): Schema
    {
        return $schema
            ->schema([
                // Section: Personal Information - Full width to allow names to breathe
                Section::make('Personal Information')
                    ->description('Primary identification and registration details.')
                    ->icon('heroicon-m-user-circle')
                    ->schema([
                        Grid::make(3)
                            ->schema([
                                TextInput::make('first_name')
                                    ->required()
                                    ->maxLength(100),
                                TextInput::make('middle_name')
                                    ->maxLength(100),
                                TextInput::make('last_name')
                                    ->required()
                                    ->maxLength(100),
                            ]),

                        Grid::make(2)
                            ->schema([
                                TextInput::make('nin')
                                    ->label('NIN')
                                    ->required()
                                    ->unique(ignoreRecord: true)
                                    ->placeholder('Enter 11-digit NIN')
                                    ->maxLength(11),

                                TextInput::make('reg_no')
                                    ->label('Registration Number')
                                    ->placeholder('Auto-generated')
                                    ->disabled() // Generated by service
                                    ->dehydrated(false),
                            ]),
                    ]),

                // Section: Status & Skills - Side by side layout
                Section::make('Professional & Eligibility Status')
                    ->icon('heroicon-m-briefcase')
                    ->schema([
                        Grid::make(2)
                            ->schema([
                                TagsInput::make('skills')
                                    ->label('Skills / Profession')
                                    ->placeholder('Type and press enter (e.g. Tailoring, Nursing)')
                                    ->columnSpan(1),

                                FileUpload::make('picture_url')
                                    ->label('Profile Photo')
                                    ->image()
                                    ->disk('public')
                                    ->directory('widow-photos')
                                    ->visibility('public')
                                    ->nullable()
                                    ->dehydrated(true)
                                    ->imageEditor()
                                    ->circleCropper(),
                            ]),

                        Grid::make(2)
                            ->schema([
                                Toggle::make('is_eligible')
                                    ->label('Eligible for Social Support')
                                    ->helperText('Verify if this widow meets standard criteria for intervention.')
                                    ->default(true),

                                Toggle::make('is_married')
                                    ->label('Remarried')
                                    ->helperText('Switch on if the widow has entered a new marriage.')
                                    ->default(false),
                            ]),
                    ]),

                // Section: Contact - Large textarea for long addresses
                Section::make('Residential Address')
                    ->icon('heroicon-m-home')
                    ->schema([
                        Textarea::make('address')
                            ->label('Physical Address')
                            ->placeholder('Street name, house number, and notable landmarks...')
                            ->rows(4)
                            ->required()
                            ->columnSpanFull(),
                    ]),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->groups([]) // This explicitly removes any inherited or persisted groups
            ->columns([
                Tables\Columns\ImageColumn::make('picture_url')
                    ->disk('public')
                    ->visibility('public')
                    ->circular()
                    ->imageSize(40),

                Tables\Columns\TextColumn::make('full_name')
                    ->label('Name')
                    ->searchable(['first_name', 'middle_name', 'last_name'])
                    ->sortable()
                    ->weight('bold'),

                Tables\Columns\TextColumn::make('nin')
                    ->label('NIN')
                    ->searchable()
                    ->copyable()
                    ->fontFamily('mono'),

                Tables\Columns\TextColumn::make('reg_no')
                    ->label('Reg No')
                    ->searchable()
                    ->badge(),

                Tables\Columns\IconColumn::make('is_eligible')
                    ->label('Eligible')
                    ->boolean()
                    ->alignCenter(),

                Tables\Columns\TextColumn::make('skills')
                    ->label('Skills')
                    ->badge()
                    ->separator(',')
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->headerActions([
                CreateAction::make()
                    ->label('Add Widow')
                    ->icon('heroicon-m-plus')
                    ->modalWidth('4xl') // Makes the creation modal wider for better layout
                    ->mutateDataUsing(function (array $data, RelationManager $livewire): array {

                        $deceased = $livewire->getOwnerRecord();

                        $generated = app(RegistrationNumberService::class)
                            ->generateWidowData($deceased);

                        return array_merge($data, $generated);
                    })
                    ->hidden(fn(RelationManager $livewire) => $livewire->getRelationship()->count() >= 4),
            ])
            ->recordActions([
                // NEW: MEDICAL RECORDS ACTION
                Action::make('manageMedical')
                    ->label('Medical')
                    ->icon('heroicon-m-beaker')
                    ->color('success')
                    ->modalHeading(fn(Widow $record) => "Medical History: {$record->full_name}")
                    ->modalWidth('5xl')
                    ->modalSubmitActionLabel('Save Updates')
                    ->fillForm(fn(Widow $record): array => [
                        'prescriptions' => $record->prescriptions()
                            ->with(['illnessModel', 'medications'])
                            ->latest('prescription_date')
                            ->get()
                            ->map(fn(Prescription $prescription): array => [
                                'id' => $prescription->id,
                                'doctor_name' => $prescription->doctor_name,
                                'illness_id' => $prescription->illness_id,
                                'prescription_date' => $prescription->prescription_date?->toDateString(),
                                'lab_test_cost' => $prescription->lab_test_cost,
                                'drug_cost' => $prescription->drug_cost,
                                'medications' => $prescription->medications->pluck('id')->all(),
                                'note' => $prescription->note,
                                'user_id' => $prescription->user_id ?? auth()->id(),
                            ])
                            ->values()
                            ->all(),
                    ])
                    ->schema([
                        Repeater::make('prescriptions')
                            ->defaultItems(0)
                            ->schema([
                                Hidden::make('id'),
                                Grid::make(3)->schema([
                                    TextInput::make('doctor_name')
                                        ->required()
                                        ->placeholder('Attending Doctor'),

                                    Select::make('illness_id')
                                        ->label('Diagnosis')
                                        ->options(fn(): array => Illness::query()
                                            ->orderBy('name')
                                            ->pluck('name', 'id')
                                            ->all())
                                        ->searchable()
                                        ->preload()
                                        ->required()
                                        ->createOptionForm([
                                            TextInput::make('name')
                                                ->required()
                                                ->unique(Illness::class, 'name'),
                                            Select::make('category')
                                                ->options(IllnessCategory::class)
                                                ->enum(IllnessCategory::class)
                                                ->required()
                                                ->native(false),
                                            Textarea::make('description')->rows(2),
                                        ])
                                        ->createOptionUsing(fn(array $data): string => Illness::create($data)->getKey()),

                                    DatePicker::make('prescription_date')
                                        ->default(now())
                                        ->required()
                                        ->native(false),
                                ]),
                                Grid::make(2)->schema([
                                    TextInput::make('lab_test_cost')
                                        ->numeric()
                                        ->prefix('₦')
                                        ->default(0),
                                    TextInput::make('drug_cost')
                                        ->numeric()
                                        ->prefix('₦')
                                        ->default(0),
                                ]),
                                Select::make('medications')
                                    ->multiple()
                                    ->options(fn(): array => Medication::query()
                                        ->orderBy('name')
                                        ->pluck('name', 'id')
                                        ->all())
                                    ->preload()
                                    ->searchable()
                                    ->hint('Search by drug name.'),
                                Textarea::make('note')
                                    ->label('Prescription Note')
                                    ->rows(2)
                                    ->placeholder('Dosage details or observations...')
                                    ->columnSpanFull(),
                                Hidden::make('user_id')
                                    ->default(auth()->id()),
                            ])
                            ->itemLabel(function (array $state): ?string {
                                $illnessName = ($state['illness_id'] ?? null)
                                    ? Illness::find($state['illness_id'])?->name
                                    : 'New Diagnosis';

                                $date = isset($state['prescription_date'])
                                    ? ' (' . date('d/m/Y', strtotime($state['prescription_date'])) . ')'
                                    : '';

                                return $illnessName . $date;
                            })
                            ->collapsible()
                            ->collapsed()
                            ->addActionLabel('New Medical Record'),
                    ])
                    ->action(function (Widow $record, array $data): void {
                        $submittedRows = collect($data['prescriptions'] ?? [])
                            ->filter(fn(array $row): bool => filled($row['doctor_name'] ?? null)
                                || filled($row['illness_id'] ?? null)
                                || filled($row['note'] ?? null));

                        $existingIds = $record->prescriptions()->pluck('id')->all();
                        $keptIds = [];

                        foreach ($submittedRows as $row) {
                            $illness = filled($row['illness_id'] ?? null)
                                ? Illness::find($row['illness_id'])
                                : null;

                            $prescription = filled($row['id'] ?? null)
                                ? $record->prescriptions()->whereKey($row['id'])->first()
                                : new Prescription();

                            if (!$prescription) {
                                continue;
                            }

                            $attributes = [
                                'doctor_name' => $row['doctor_name'] ?? null,
                                'illness_id' => $row['illness_id'] ?? null,
                                'prescription_date' => $row['prescription_date'] ?? now()->toDateString(),
                                'lab_test_cost' => $row['lab_test_cost'] ?? 0,
                                'drug_cost' => $row['drug_cost'] ?? 0,
                                'note' => $row['note'] ?? null,
                                'user_id' => $row['user_id'] ?? auth()->id(),
                            ];

                            if (DatabaseSchema::hasColumn('prescriptions', 'illness')) {
                                $attributes['illness'] = $illness?->name ?? 'Unspecified diagnosis';
                            }

                            $prescription->fill($attributes);

                            if (!$prescription->exists) {
                                $prescription->prescribable()->associate($record);
                            }

                            $prescription->save();
                            $prescription->medications()->sync($row['medications'] ?? []);

                            $keptIds[] = $prescription->id;
                        }

                        $idsToDelete = array_diff($existingIds, $keptIds);
                        if ($idsToDelete !== []) {
                            $record->prescriptions()->whereKey($idsToDelete)->get()->each(function (Prescription $prescription): void {
                                $prescription->medications()->detach();
                                $prescription->delete();
                            });
                        }

                        $record->touch();

                        Notification::make()
                            ->title('Medical records updated')
                            ->success()
                            ->send();
                    }),

                ViewAction::make(),
                EditAction::make()->modalWidth('4xl'),
                DeleteAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
